//create variables and elements
// var answerBt = document.querySelectorAll(".choices");
var startBtn = document.querySelector("#start-button");
var promptTextEl = document.querySelector("#prompt");
var gameTimerEl = document.querySelector("#timer");
var quizBodyEl = document.querySelector("#quiz");
var questionBodyEl = document.querySelector("#question-container");
var scoreEl = document.querySelector("#score-container");
var submitBtn = document.querySelector("#submit-button")
var userInput = document.querySelector("#user-text");
var highScore = document.querySelector("#high-score-cont")
var quizStarted= false;
var timeLeft = 60;
var timerInterval;
var userScore= 0;
var currentQuestion = 0;
var quizChoice = "";
var userInitials;
var myQuestions = [
{
    question: "What is JavaScript?",
    answers:["A programming language","Food","A tourist spot","A hidden city"],
    correctAnswer: "A programming language" 
}, 
{ 
    question: "Is JavaScript Strongly or weakly typed?", 
    answers: ["Strongly","Weakly"], 
    correctAnswer: "Weakly" 
}, 
{ 
    question: "What year was JavaScript released?", 
    answers:[1990,1986,1870,1995], 
    correctAnswer: 1995
},
{
    question: "What is the JavaScript filetype?",
    answers:[".js",".doc",".jsc",".exe"],
    correctAnswer: ".js"
},
{
    question: "What type of language is JavaScript?",
    answers:["Javanese","Syntax Secure","Object Oriented","Coffee Code"],
    correctAnswer: "Object Oriented"
}

  
]
// start the clock and reset important values
function timer(){
    if(quizStarted == false){
        console.log("yay")
        timeLeft = 60;
        currentQuestion= 0;
        userScore= 0;
        scoreEl.textContent = "";
        gameTimerEl.textContent = timeLeft;
        quizStarted= true;
        timerInterval = setInterval(function(){
            timeLeft--;
            gameTimerEl.textContent = timeLeft;
            if(timeLeft === 0){
                clearInterval(timerInterval);
                gameOver();
            }
        },1000);
     }
}

//present quiz and start timer
function generateQuiz(){
    if(quizStarted == false){
    showQuestions(currentQuestion)
    timer()
    }
//showquestions(){
//clear the current question and possible answers
//increase myquestion index
//display new question and possible answers
//}
}

//WHEN I answer a question
//THEN I am presented with another question

//show questions and generate buttons related to current question
function showQuestions(indexQuestion){

    console.log(myQuestions[indexQuestion])
    var test = myQuestions[indexQuestion].answers;
    var prompt = myQuestions[indexQuestion].question;
    promptTextEl.textContent = prompt;
    scoreEl.textContent = "";
        for(var i = 0; i < test.length; i++){
            console.log(test[i]);
            var newBtn = document.createElement("button");
            newBtn.innerHTML = test[i];
            newBtn.value = test[i]
            newBtn.className = "choices";
            questionBodyEl.appendChild(newBtn);
            newBtn.addEventListener("click", myQuizGame);            
            }
            
//console.log(quizBodyEl);
}

//advance the quiz as well as increment score/decrease timer for correct/wrong answers
//additionally remove buttons generated by the show questions button after an answer is made
function myQuizGame(){
    let removalEl= questionBodyEl;
    if(currentQuestion < myQuestions.length-1){
            var quizChoice = this.innerHTML;
            var test2 =myQuestions[currentQuestion].answers;
            var queryAnswer = myQuestions[currentQuestion].correctAnswer;
            console.log(quizChoice);
            console.log(queryAnswer)
            //increase score if answer is correct, remove previos questions, and move to the next question
            if(quizChoice == queryAnswer){
                console.log("nice");
                userScore++
                currentQuestion++;
                while(removalEl.firstChild){
                    removalEl.removeChild(removalEl.firstChild);
                }
                showQuestions(currentQuestion);
                console.log(currentQuestion)
                console.log(myQuestions.length)
            }
            //decrease time remaining if answer is incorrect, remove previos questions, and move to the next question
            else if(quizChoice != queryAnswer && timeLeft >= 6){
                console.log("damn");
                currentQuestion++;
                timeLeft -= 5;
                gameTimerEl.textContent = timeLeft;
                while(removalEl.firstChild){
                    removalEl.removeChild(removalEl.firstChild);
                }
                showQuestions(currentQuestion);
                console.log(currentQuestion)
                console.log(myQuestions.length)
            } 
            //decrease time remaining if answer is incorrect and set timer to 0 and end the quiz as time has run out
            else{
                console.log("damn");
                currentQuestion++;
                timeLeft = 0;
                gameTimerEl.textContent = timeLeft;
                while(removalEl.firstChild){
                    removalEl.removeChild(removalEl.firstChild);
                }
                gameOver();
            }
    }
        else{
            while(removalEl.firstChild){
                removalEl.removeChild(removalEl.firstChild);
            gameOver();
        }
    }
}
//end the game and display the score from the quiz/ allow another quiz to start
function gameOver(){
    quizStarted =false;
    clearInterval(timerInterval);
    userScore += timeLeft;
    console.log(userScore)
    timeLeft = 0
    gameTimerEl.textContent = timeLeft;
    console.log("Game Over!")
    scoreEl.textContent = "Score: " + userScore;
    promptTextEl.textContent= "Game over~! Enter initials and save high score?"

}

//submit the current score as well as entered initials by user
function submitHighScore(event){
    event.preventDefault();
    var userText = userInput.value.trim();
    if (userText === "" || scoreEl.innerHTML == "") {
      return;
    }
    //prevents submission during the quiz as well as if the quiz has not been completed
    if( userScore != 0 && quizStarted == false){
    promptTextEl.textContent= "Thanks for playing! Click the start button if you want to try again."
    userInitials = userText
    highScore.innerHTML = "Current High Score: " + userInitials + " " + userScore;
    }
    else{
        promptTextEl.textContent= "You must finish the quiz to submit your score! Click the Start button if you have not already!"
    }
}

//click handlers
startBtn.addEventListener("click", generateQuiz);
submitBtn.addEventListener("click", submitHighScore);